const Tips = [
  {
		id: 1,
		title: 'HOW LONG DOES THE CORONAVIRUS LIVE ON CLOTHES: WILL LAUNDRY DETERGENT KILL THE VIRUS?',
		paragraph: [
			{
				title: "",
				image: "",
				content: "Coronavirus is gradually overtaking the whole world, and it is everywhere. It infects humans across all the ages, gender and nationalities. Healthcare professionals are solely focussing on managing the disease. The Governments are working on minimising the spread and handling the mounting tensions. Trade and commerce have come to a standstill. This also tremendously decreases travel and transportation options. The fear and paranoia of the disease have been rampant. The definite mode of transmission is not transparent yet. The current research states a person can be affected through respiratory droplets from an infected individual. Though this is the primary mode of communication, it is too early to determine the other modes. The Coronavirus can survive on various surfaces. The shelf life is highly unclear at this specific point. Some researchers say that the virus can live up to 24 hours on some materials. This is a scary thought that calls for absolute protection and cares at all times. This leads us to the critical question of all. How long does the coronavirus live in clothes? Will laundry detergent will enough to kill the virus? Should I hire an online dry cleaning service? Here are some precautions and steps that people can take to minimise the risk."
			},
			{
				title: "Should I Wash The Clothes Every Time After Going Out?",
				image: "",
				content: "It is advisable to wash these clothes immediately after going out. Though we follow social distance, there is always the possibility that people might encounter an infected person at close quarters. It is essential to clean the entire outfit and dry them in sunlight thoroughly. This would kill the coronavirus that might be present in the dresses."
			},
			{
				title: "Should I Take More Precautions If I Visit A High-Risk Area?",
				image: "",
				content: "The risk of coronavirus increases if a person visits the high-risk areas. It is sensible to stay away from these regions under any circumstances. However, if there is a justifiable reason to visit, then wash the clothes immediately with a strong detergent and disinfectant. The dry cleaning services in Gurgaon can handle these challenges. The Government provides specific guidelines on how to handle this situation."
			},
			{
				title: "What Are The Steps To Be Taken To Wash The Clothes Of A Quarantined Person?",
				image: "",
				content: "The home quarantine protocol segregates people who have been exposed to the virus from society. Though they do not have symptoms, there is a possibility that they could have contracted the coronavirus. It is essential to be in self-isolation to protect their family. Their clothes should be washed separately, preferably with disposable gloves. Avoid touching the dresses with bare hands. Always wash the hands with sanitiser or disinfectant after the laundry process. The guidelines also ask people to avoid shaking the clothes to prevent dispersion. It is also crucial to disinfect the clothing hamper, clips, and lines to stop transmission to other garments and people."
			},
			{
				title: "Is It Mandatory To Wash The Clothes By A Machine?",
				image: "",
				content: "It is better to wash clothes by a machine during the current situation. Heat tends to kill the coronavirus more effectively. The heat generated by the washing machine would be adequate to destroy the organisms. It is also safer than hand washing as it protects the person washing them from contracting the virus. You can also outsource it to an online dry cleaning service that has the industrial setup."
			},
			{
				title: "Should We Wait For A Specific Duration To Wash The Clothes?",
				image: "",
				content: "Coronavirus has a specific shelf life in different materials. It is natural for people to consider washing the clothes after that duration for safety purposes. However, there is no quantitative information available on the subject. People can use gloves to minimise the risk."
			}
		],
		post_date: "06/12/2020",
		banner: require("../../assets/articles/1/banner.png")
	},
	{
		id: 2,
		title: "7 CLOTHING CARE MYTHS YOU SHOULD STOP BELIEVING",
		paragraph: [
			{
				title: "",
				image: "",
				content: "There is always a thin line between myth and reality.  Notable online laundry in Gurgaon is helping to check the reliability of the data. Most information from the yesteryears was not digitalised. People passed the information through word of mouth. This is especially true for household recipes and secrets. Our grandmothers and ancestors did not write their knowledge and experience in paper. They taught their daughters and close relatives about the subject."
			},
			{
				title: "",
				image: "",
				content: "They shared their finding with their neighbours and traded their secrets for more exciting data. This enabled them to expand their understanding and upgrade their skills in household activities. There is no written manuscript for these unique recipes and tricks. Some of this information was forgotten, lost or even ignored."
			},
			{
				title: "",
				image: "",
				content: "Some data was changed due to miscommunication and lack of understanding of the subject. This paved the way for myths and misconceptions in domestic activities. Most people would agree that our ancestors have great information about various essential things. However, this data has been twisted and changed by oversight or error."
			},
			{
				title: "",
				image: "",
				content: "The clothing care segment has many such misconceptions that can do more harm than good. The first step in identifying this information is to eliminate false data. Here are seven clothing myths that you should stop believing."
			},
			{
				title: "Quantity Does Not Guarantee Quality",
				image: "",
				content: "The most common misconception about clothes washing is the amount of detergent usage. Some people assume that more detergent is always better in removing the dirt and stains. However, there are only so many chemicals that the dresses can handle. The excess powder would settle in the fabric and compromise the quality. It is vital to utilise the recommended for the benefit of the clothes and the environment. Online laundry service Gurgaon use the right amount and product to protect your dresses."
			},
			{
				title: "Stain Removal Techniques",
				image: "",
				content: "Stains can be tough on clothes, like so many things in life. On the same note, we do get loads of bad advice on how to handle it. Every stain reacts to different removal materials and techniques. This information is passed through the family vine and available online. The ideal methodology would be to rinse it with water immediately and deploy the ideal solution. It is critical to make a note of these techniques that work well for future reference. You can also hire an online laundry Gurgaon service for expert touch."
			},
			{
				title: "Heat Shrinks Clothes",
				image: "",
				content: "Clothes shrinkage is a common issue faced by all people. Though we often blame the quality of the dresses, the washing technique could also be a contributing factor. Despite popular belief, excessive heat is not the real culprit. Lack of moisture causes the dresses to shrink."
			},
			{
				title: "Bleach And Detergent Don’t Mix",
				image: "",
				content: "Bleach is generally bleach to remove stains from clothes. However, it should never be added along with the cleanser. The combination of both elements can be harmful to the dresses. Bleach can also negatively impact the functionality of the detergent."
			},
			{
				title: "The Washing Frequency",
				image: "",
				content: "Some clothes like jeans do not require a steady washing frequency. They can be cleaned occasionally to maintain quality and value. It is different for each material and should be followed accordingly."
			},
			{
				title: "The Literal Meaning Does Not Qualify",
				image: "",
				content: "It is vital to recognise the real meaning behind the washing and laundry techniques. Dry Cleaning does not signify the lack of fluids. Laundry companies use specific chemicals for this process. Similarly, consumers can utilise a gentle machine-washing option for the hand wash instructions. "
			},
			{
				title: "Water Temperature",
				image: "",
				content: "The water temperature does not have a direct impact on the washing process. Hot water and cold water cannot kill bacteria or at least independently. It is imperative to use the right detergent to accomplish the task."
			},
		],
		post_date: "30/11/2020",
		banner: require("../../assets/articles/2/banner.png")
	},
	{
		id: 3,
		title: "10 LAUNDRY PROBLEMS AND HOW TO FIX THEM",
		paragraph: [
			{
				title: "",
				image: "",
				content: "Washing clothes inclusive of online Laundry Service might seem like a simple process. What could go wrong in loading the clothes in a machine? What could go wrong when we dry the dresses in the natural light? Many laundry problems could spoil the quality of your favourite outfits. Most people have experienced laundry mishaps at some point or other. Though they attempt to rectify the mistakes, the damage is already done."
			},
			{
				title: "",
				image: "",
				content: "Even the most expensive clothes can lose its value with a simple mistake. This can be due to oversight or maybe sometimes, due to genuine ignorance. It is essential to know the problem and cause to avoid it in the future. Most people have a particular technique which helps them and others to prevent those mistakes. Here are 10 Know-how on laundry problems and Laundry tips on how to fix them."
			},
			{
				title: "1. Know How To Prevent Shrinkage Of Clothes",
				image: "",
				content: "Certain clothes tend to shrink after washing them. This does not always mean that we have gained a few extra pounds, or the material is of low quality. This could also mean that we have utilised the wrong technique while doing laundry. Excessive heat in the water or machine can cause clothes to shrink. It is essential to check the washing instructions well in advance.  It is critical to follow the service and repair schedule of the washing machine to avoid the device to overheat. There are online dry cleaning services in Gurgaon who might help to prevent the problem"
			},
			{
				title: "2. Know How To Prevent Holes And Tear",
				image: "",
				content: "Some clothes tend to tear while in the machine and even during a hand wash. This can be due to the usage of harsh detergents which disrupts the fibres. This can be due to excessive scrubbing of the dresses in an attempt to remove the dirt. If the machine has a loose metal screw or part, then it could cause holes in the suit. Avoiding these factors would prevent damage to the clothes."
			},
			{
				title: "3. Know How To Avoid Bleeding",
				image: "",
				content: "What is bleeding? Before you imagine scary horror movies, this topic is strictly limited to clothes and are equally traumatizing. Sometimes, the dyes used for coloring the materials do not stick in them. They tend to dissolve during laundry and attach themselves to other dresses. This can be a mass disaster as all the clothes are damaged in the process. Always watch the new garments separately, especially the bright ones."
			},
			{
				title: "4. Know How To Remove Stains",
				image: "",
				content: "Stains can be a nightmare, and it is difficult to get rid of them. It cannot be avoided, especially for people with children and those working in stain prone industries. Time is the essence when it comes to stain removal. It is essential to familiarise yourself with the different stain removal mechanisms. This not only helps with the removal but also prevents the spread of the marks."
			},
			{
				title: "5. Know How To Avoid Stains",
				image: "",
				content: "There is a high probability that the clothes might be stained due to oversight. Do you have kids who love crayons? Do you have the habit of leaving the pen in your pocket? This small mistake can cost a whole batch of clothes. The stain removal is a challenge when it comes to these types of stain. Always check the pockets before loading it in the machine. A good toss and shake can also be a good idea to prevent these laundry problems."
			},
			{
				title: "6. Know How To Prevent Colour Loss",
				image: "",
				content: "Dresses can lose their colour while washing and drying. This is mainly due to the usage of harsh chemicals and hot water. The substances have a damaging effect on the dyes of the clothes. If it is incredibly harsh, then it can cause the entire area to whiten and leave patches in specific areas. Always check the ingredient list and read reviews before choosing the washing detergents."
			},
			{
				title: "7. Know How To Utilise The Equipment Properly",
				image: "",
				content: "A washing machine is a miracle appliance that played a crucial role in women empowerment. The equipment was developed to ease the domestic work of women and help them concentrate on more critical issues. It is the responsibility of every woman and man to remember the history and utilise it wisely."
			},
			{
				title: "8. Know How To Avoid Fading",
				image: "",
				content: "Fading is the terminology used when clothes become dull and lose their original aesthetic value. There are various reasons for which the garments might undergo this damage. Other the washing mistakes, the wrong drying technique can be a substantial contributing factor."
			},
			{
				title: "9. Know How To Measure Your Detergent",
				image: "",
				content: "How much detergent is too much? How much soap is too less? There is no right answer to this query. However, the wrong answer might damage the clothes and the machine. It is essential to calculate this level by the number and nature of the dresses. Certain materials can withstand the harshness of the chemicals. Some items are soft and are more susceptible to damage."
			},
			{
				title: "10. Know How To Prevent Ironing Mishaps",
				image: "",
				content: "When we think about laundry, it is natural to consider only the washing aspect. However, it also includes the ironing part. It is vital to purchase the right machine based on the electricity utility. Always read the instructions in the clothes and appliance manual before proceeding with the process."
			},
			{
				title: "",
				image: "",
				content: "Laundry service is a basic necessity for all humans. This information can help you to avoid mishaps and accidents which washing clothes. It is essential to be alert and careful while sorting the dresses. Always read the manual for the equipment, detergents and even the clothes. This will aid in proper utilisation and extends the life of the products. You can also seek assistance from online laundry service providers. Many professional companies in the area offer quality services."
			},
		],
		post_date: "23/11/2020",
		banner: require("../../assets/articles/3/banner.png")
	},
	{
		id: 4,
		title: "How to Remove Coffee and Tea Stains",
		paragraph: [
			{
				title: "",
				image: "",
				content: "Mornings are difficult as it is, and sometimes drips and spills from your morning brew can leave unsightly stains on your clothes. Coffee stains or tea stains don't have to ruin your morning if you act fast to treat them.Start by blotting the stain and then running cold water over it. Pre-treating is critical, so after you've rinsed the stain, work in a detergent like Tide Ultra Stain Release Liquid using a soft-bristled toothbrush. You can always repeat the pre-treating steps until you're satisfied, just remember not to tumble dry until the stain is gone, as drying will set coffee and tea stains permanently. Read on for Tide’s step-by-step guide to coffee and tea stain removal:"
			},
			{
				title: "1. Pre-Treat",
				image: require("../../assets/articles/4/step1.png"),
				content: "Run cold water over the stain. Pour Tide Ultra Stain Release Liquid detergent onto the stain and rub the fabric together gently or use a soft bristled toothbrush to help work the detergent into the fibers of the garment. Then let it stand for a few minutes."
			},
			{
				title: "2. Dose",
				image: require("../../assets/articles/4/step2.png"),
				content: "Use the cap to ensure you use the right amount of detergent. Just fill it with the correct dose of detergent, and pour it into the detergent dispenser if you have an HE machine, or directly into the drum before loading the clothes if you have a non-HE machine."
			},
			{
				title: "3. Wash",
				image: require("../../assets/articles/4/step3.png"),
				content: "Wash as usual with Tide, making sure you dose correctly. Always make sure to follow the instructions on your garment’s care label."
			},
			{
				title: "4. Unload",
				image: require("../../assets/articles/4/step4.png"),
				content: "When the wash cycle is over, remove the items and you’re ready to go."
			},
			{
				title: "",
				image: "",
				content: "If the stain persists after washing, repeat the previous steps before tossing in the dryer, as drying will set the stain."
			}
		],
		post_date: "16/11/2020",
		banner: require("../../assets/articles/4/banner.png")
	},
	{
		id: 5,
		title: "Why Is My Washing Machine Leaking?",
		paragraph: [
			{
				title: "",
				image: "",
				content: "Is your washer leaking? Here are the top five reasons, plus simple tips on how to fix the most common washing machine problems."
			},
			{
				title: "",
				image: "",
				content: "Got a puddle of water on the floor after doing a load of laundry? Don’t panic. It could be a simple problem with a DIY fix. The key to finding the cause of the leak is to try to identify where the water is coming from and exactly when in the cycle it appears, explains Jeffrey McBride, a Sears Home Services laundry expert."
			},
			{
				title: "1. The hoses aren’t secure.",
				image: "",
				content: "Check your hoses first. The fill hoses are normally located at the rear of the washer. Are the threaded fittings tightened? The drain hose is also located at the rear of the machine and may not be properly installed into the household drain. Verify that the leak is not caused by a restricted household drain that’s backing up through the standpipe."
			},
			{
				title: "2. The door isn’t fully closed or the door seal is damaged.",
				image: "",
				content: "Water coming from the door is the easiest to spot. First, make sure the door is fully closed. Is a sock trapped between the seal and the door? Problem solved. If the door is closed all the way, check the seal itself for erosion or damage. If the seal looks fine, try cleaning it. Bits of cotton, undissolved washing machine detergent, hair and other small offenders can all cause a leak. Use a scouring pad or a similar object to clean the door as well."
			},
			{
				title: "3. The water pressure is too high.",
				image: "",
				content: "When a soap drawer leaks on a front-load washer, it will almost invariably be for one of two reasons: Either the incoming water pressure is too high, causing water to spill over the top, or something is blocking the flow of water. Simple fix? Turn the water pressure down a bit using the tap at the connection point for your washing machine."
			},
			{
				title: "4. The dispenser is blocked.",
				image: "",
				content: "Usually, using too much detergent will cause a blockage in the dispenser drawer, which will, in turn, make the water overflow. Clean the drawer with hot water and a brush."
			},
			{
				title: "5. You’re using too much detergent.",
				image: "",
				content: "If your washer is oversudsing, you’re using too much detergent. Reduce oversudsing with a mixture made from 8 parts water to 1 part vinegar before doing another load with less detergent. About 1 quart of this mixture should dissipate the suds."
			},
			{
				title: "",
				image: "",
				content: "These are all relatively easy fixes — but for anything more serious, like internal hose failures, a faulty water inlet valve, a pump issue or seals that need to be replaced, call a service technician to come out and take a look."
			}
		],
		post_date: "09/11/2020",
		banner: require("../../assets/articles/5/banner.png")
	},
	{
		id: 6,
		title: "6 Things You are Probably Doing Wrong While You Do Laundry",
		paragraph: [
			{
				title: "",
				image: "",
				content: "One of the many tasks every adult has to deal with on a regular basis is doing the laundry. Most adults do their laundry at home least once a week, however, they are never able to get the results professional laundry service providers give. Why? Is the public doing their laundry wrong or the professionals have some magic potions? Actually, both are true. Professionals do have access to some extraordinary laundry products but most adults are doing one of the following six things, which are producing poor results for them."
			},
			{
				title: "1. Overloading the cycle",
				image: "",
				content: "Yes, it seems like a time saver, and you might think just a few extra articles in your load will not hurt, but you are wrong. Your clothes will not come out as clean as they should, and you will end up washing all those again, so what would be the point of all of this? Do not overload your washer."
			},
			{
				title: "2. Using the wrong detergent",
				image: "",
				content: "Top Load machines and front load machines require different detergents. Different kinds of washing machine manuals indicate what kind of detergent will work best with that particular model, yet so many people do not even bother to go through the complete manual and end up using the wrong detergent for years. This leads to the machine not performing to its best capacity of cleaning. Also, some detergents are too harsh for delicate natural fabrics, so you should keep this in mind too. Similarly, detergents designed for delicate wash might not clean the tougher garments efficiently."
			},
			{
				title: "3. Wrong amount of detergent",
				image: "",
				content: "Most detergents and washing machines come with the recommendation of the optimal amount of detergent to be used per load. It should be obvious using less detergent will lead to clothes not properly cleaned, but using more detergent does not equate cleaner clothes either, in fact, it’s the other way around. Too many detergents may leave residue on your clothes which will appear as suds. Pay attention to the correct measurement of detergent recommended for each load for the best results."
			},
			{
				title: "4. Care labels on clothes",
				image: "",
				content: "Just like machine manuals very few people pay any heed to care labels attached to clothes. Not all clothes can be machine washed and even if they can be, specific water temperature is more suitable to wash them or they might need to be put in a light load or require a rinse afterwards. Not paying attention to care labels may be the cause of clothes coming out slightly dirty, shrunken or overly wrinkled."
			},
			{
				title: "5. Using cold water and same machine settings for everything",
				image: "",
				content: "Most people mindless get into a routine of throwing everything in cold water handset up same washing machine setting for everything. While cold water is a safe bet generally, not all stains will come off in cold water. Similarly, not all types of fabric will fir in your standard machine settings. Sort your clothes beforehand, not just the whites and colours but also sort them according to fabric type and how dirty the particular article is. Be mindful of what settings you are using for each load."
			},
			{
				title: "6. Not maintaining your machine",
				image: "",
				content: "It’s important to take care of your washing machine so it can take care of your clothes. For a machine to clean your clothes to its best potential, it should be in the best shape. If you have not been inspecting your machine for faults and repairs every month you might be responsible for the poorly washed clothes. You also need to clean your washing machine from inside at least every other week. This will ensure there is no lint or residue accumulated and nothing is catching rust or mould. A machine in good condition will need less water, less detergent and will clean clothes better."
			}
		],
		post_date: "02/11/2020",
		banner: require("../../assets/articles/6/banner.png")
	},
	{
		id: 7,
		title: "Removing Makeup Stains Tips from Laundry Service Company",
		paragraph: [
			{
				title: "",
				image: "",
				content: "Making up stains are trickier than your average stains as they are highly pigmented and oil-based. Such strains are referred to as combination stains and must be treated in a particular order to be efficiently removed. Mostly hydrogen peroxide bleach or alcohol-based stain removers are believed to be of help in such situations, but a lot depends upon the colour and type of fabric and."
			},
			{
				title: "",
				image: "",
				content: "As a general rule of thumb, do not try to wipe the stain out using a wet wipe or paper towel, it can spread the stain or further set in the stain. Let it sit and dry out. When the stain is dried,  apply some dishwashing detergent to get the oily part. Rinse off after half an hour and then apply some enzymatic presoak for another thirty minutes. Rise again and pour some oxygenized non-chlorine bleach over the spot to lift off the most stubborn stains known to women around the globe."
			},
			{
				title: "Foundation Stains",
				image: "",
				content: "Foundation is as rich in its oily content as it is highly pigmented. Avoid wiping off the stain with the hand as the heat from your hand will melt the foundation and rub it further in the fabric. Instead, use a plastic card or spoon to lift off the excess and let the rest sit and dry so you are not spreading it. You can also try to rub an ice cube on in the meanwhile. Follow up with the above-given method of dishwashing liquid, enzymatic presoak and oxygenized non-chlorine bleach. "
			},
			{
				title: "Powder",
				image: "",
				content: "Don’t try to brush off the powder with your finger for the same reason mentioned above, blow away the powder (but do not use a blow dryer as recommended on some places online because the heat will melt powder in the fabric) or brush it off with a makeup brush. Or simply use a makeup wipe to pick up the powder from the surface. Pour a few drops of liquid soap on the spot, rub gently and rinse off."
			},
			{
				title: "Lipstick",
				image: "",
				content: "An alcohol-based hygiene wipe can be excellent emergency treatment. Place the wipe over the stain and gently tap the surface area, without actually rubbing the wipe on the stain so you are not pushing down the oil and pigments further in the fabric. If you have some acetone, rubbing alcohol, cheap perfume or hair spray, soak the spot in it and let it sit for a few seconds then wipe off with a paper towel. This should effectively clean the stain."
			},
			{
				title: "Nail Polish",
				image: "",
				content: "If you have an ice cube near by using it to quickly dry and chip off the excess of the nail polish. Let the nail polish dry and do not try to wipe the stain away while it’s still wet as this will just spread the stain. Once the nail polish is dry, use a cotton swab soaked in rubbing alcohol to lift up as much of stain as possible. Pat dry with a clean paper towel. Use acetone or a few drops of your regular nail polish remover on the nail polish stain and lift up the nail polish using a paper towel or cotton swab. Once the nail polish is gone you will be left with a light yellowish stain of acetone or alcohol. That will easily go away during your regular laundry wash."
			},
			{
				title: "Mascara",
				image: "",
				content: "We have already established no touching to makeup stains with bare hands as heat is never good for oil-based pigmented stains, let the excess dry and scrape off the chunky stuff using a plastic card or an old toothbrush. Use a makeup removing wipe to take as much mascara as you can and then toss it into your washing machine with your laundry. "
			}
		],
		post_date: "26/10/2020",
		banner: require("../../assets/articles/7/banner.png")
	},
];

const Promo = [
  {
    id: 1,
    banner: require('../../assets/images/promo-new.jpg'),
    title: 'Get 50% discount for new customer',
    desc: '50% discount for your first checkout in Laundry App.',
	code: 'NEWCUSTOMER50',
	expired: null,
	pieces: 1
  },
  {
    id: 2,
    banner: require('../../assets/images/promo-bag-shoes.jpg'),
    title: '10% off to clean your bag and shoes',
    desc: 'Need to clean your bag and shoes ? Clean with us and enjoy this 10% discount',
	code: 'BAGSHOES10',
	expired: "31/01/2021",
	pieces: 2
  },
  {
    id: 3,
    banner: require('../../assets/images/promo.jpg'),
    title: 'Special December promo',
    desc: 'Enjoy this special free delivery fee in December only.',
	code: 'FLASHDECEMBER',
	expired: "31/12/2020",
	pieces: 1
  },
  {
    id: 4,
    banner: require('../../assets/images/promo-20.jpg'),
    title: 'Get 20% off for 50 KG clothes',
    desc: 'Discount 20% for minimum 50 KG clothes ( does not apply to express laundry services ) ',
	code: 'LAUNDRY20',
	expired: null,
	pieces: 2
  }
];

export { Tips, Promo };